FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-build AS build

# Install build tools and remove apt-cache afterwards
RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	build-essential \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch into our apps working directory
WORKDIR /usr/src/app

# Copy all the app source into docker context
COPY . /usr/src/app

# Build our binary
RUN g++ -o bmp bmp.cpp